PROGRAMS = {
    "ICE": {
        "department_code": "SOCIE",
        "name": "Information and Communication Engineering",
    },
    "CSE": {
        "department_code": "SOCIE",
        "name": "Computer Science and Software Engineering",
    },
    "BA": {
        "department_code": "BUSLOG",
        "name": "Business Administration",
    },
    "SBL": {
        "department_code": "BUSLOG",
        "name": "Logistics Management",
    },
}


CURRICULA = {
    "ICE": [
        ("General", "GEN1011", "Academic English 1", 2, True),
        ("General", "GEN1012", "Academic English 2", 2, True),
        ("General", "GEN1020", "Academic English Reading", 2, True),
        ("General", "GEN2010", "Technical Writing & Discussion", 2, True),
        ("General", "GEN2021", "Academic English 3", 2, False),
        ("General", "GEN2022", "Academic English 4", 2, False),
        ("General", "GEN2031", "Basic Korean 1", 1, False),
        ("General", "GEN2032", "Basic Korean 2", 1, False),
        ("Non-Technical", "NTS3010", "Introduction to Business Administration", 3, True),
        ("Non-Technical", "NTS3040", "Introduction to Economics", 3, True),
        ("Non-Technical", "NTS3050", "Introduction to Logistics Management", 3, False),
        ("Non-Technical", "NTS4020", "Korean Technology Development Strategy", 3, False),
        ("Non-Technical", "NTS4050", "Understanding Intellectual Property Rights", 3, False),
        ("Non-Technical", "NTS3020", "Engineering Communications", 3, True),
        ("Non-Technical", "NTS4010", "Engineering Ethics", 2, True),
        ("Non-Technical", "NTS4060", "Distinguished Lecture in Social Science and Art", 2, False),
        (
            "Non-Technical",
            "NTS4070",
            "Distinguished Lecture in Natural Science and Technology",
            2,
            False,
        ),
        ("Non-Technical", "NTS4080", "Comtemporary Topics and Trends", 2, False),
        (
            "Non-Technical",
            "NTS3031",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-1",
            1,
            True,
        ),
        (
            "Non-Technical",
            "NTS3032",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-2",
            1,
            True,
        ),
        ("Technical Fundamental", "MSC1010", "Math Pre-calculus", 3, False),
        ("Technical Fundamental", "MSC1011", "Calculus 1", 3, True),
        ("Technical Fundamental", "MSC1012", "Calculus 2", 3, True),
        ("Technical Fundamental", "MSC2010", "Engineering Mathematics", 3, True),
        ("Technical Fundamental", "MSC2020", "Linear Algebra", 3, True),
        ("Technical Fundamental", "MSC2050", "Discrete Mathematics", 3, True),
        ("Technical Fundamental", "MSC3010", "Probability and Statistics", 3, True),
        ("Technical Fundamental", "MSC1020", "Science Pre-physics", 3, False),
        ("Technical Fundamental", "MSC1021", "Physics 1", 3, True),
        ("Technical Fundamental", "MSC1022", "Physics 2", 3, True),
        ("Technical Fundamental", "MSC1031", "Physics Experiment 1", 1, True),
        ("Technical Fundamental", "MSC1032", "Physics Experiment 2", 1, True),
        ("Technical Fundamental", "MSC1051", "S/W Object-Oriented Programming 1", 3, True),
        ("Technical Fundamental", "MSC1052", "Object-Oriented Programming 2", 3, True),
        ("Technical Fundamental", "MSC2070", "Application Programming in Java", 3, True),
        ("Technical Core", "ICE1010", "Introduction to IT", 3, True),
        ("Technical Core", "ICE1020", "Creative Engineering Design", 3, True),
        ("Technical Core", "SOC2020", "Digital Logic Circuit", 3, True),
        ("Technical Core", "ICE2120", "Circuit and Lab", 3, True),
        ("Technical Core", "ICE3110", "Signals and Systems", 3, True),
        ("Technical Core", "SOC3030", "Computer Algorithm", 3, True),
        ("Technical Core", "SOC3010", "Operating System", 3, True),
        ("Technical Core", "SOC3020", "Database", 3, True),
        ("Technical Core", "SOC3040", "Computer Networks", 3, True),
        ("Technical Core", "ICE4020", "Capstone Design", 3, True),
        ("Technical Elective", "ICE2010", "Data Structure", 3, False),
        ("Technical Elective", "SOC2110", "Internet Programming", 3, False),
        ("Technical Elective", "SOC2040", "System Programming", 3, False),
        ("Technical Elective", "SOC2060", "Computer Architecture", 3, False),
        ("Technical Elective", "ICE2080", "Electronic Circuit", 3, False),
        ("Technical Elective", "SOC3050", "Embedded Software & Design", 3, False),
        ("Technical Elective", "SOC3060", "Database Application & Design", 3, False),
        ("Technical Elective", "SOC3070", "System Analysis", 3, False),
        ("Technical Elective", "SOC4010", "Computer Security", 3, False),
        ("Technical Elective", "SOC4020", "Multimedia Computing", 3, False),
        ("Technical Elective", "SOC4030", "Mobile Programming", 3, False),
        ("Technical Elective", "SOC4040", "Artificial Intelligence", 3, False),
        ("Technical Elective", "SOC4050", "Computer Graphics", 3, False),
        ("Technical Elective", "SOC4060", "Game Programming", 3, False),
        ("Technical Elective", "SOC4080", "Multimedia Application", 3, False),
        ("Technical Elective", "SOC4090", "E-Commerce", 3, False),
        ("Technical Elective", "SOC4100", "Information Systems Security", 4, False),
        ("Technical Elective", "SOC4110", "Internet of Things", 3, False),
        ("Technical Elective", "SOC4120", "Mobile Communication", 3, False),
        ("Technical Elective", "SOC4130", "Data Communication", 3, False),
        ("Technical Elective", "SOC4140", "Theory of Programming language", 3, False),
        ("Technical Elective", "SOC4150", "Wireless Communications", 3, False),
        ("Technical Elective", "SOC4170", "Big Data Analytics", 3, False),
        ("Technical Elective", "SOC4180", "Deep Learning for Computer Vision", 3, False),
        ("Technical Elective", "ICE4010", "Digital Signal Processing", 3, False),
        ("Technical Elective", "ICE4011", "Internship 1", 3, False),
        ("Technical Elective", "ICE4012", "Internship 2", 3, False),
    ],
    "CSE": [
        ("General", "GEN1021", "Academic English 1", 2, True),
        ("General", "GEN1022", "Academic English 2", 2, True),
        ("General", "GEN1020", "Academic English Reading", 2, True),
        ("General", "GEN1030", "Technical Writing & Discussion", 2, True),
        ("General", "GEN2021", "Academic English 3", 2, False),
        ("General", "GEN2022", "Academic English 4", 2, False),
        ("General", "GEN2033", "Basic Korean 1", 2, False),
        ("General", "GEN2034", "Basic Korean 2", 2, False),
        ("Non-Technical", "NTS3010", "Introduction to Business Administration", 3, True),
        ("Non-Technical", "NTS3040", "Introduction to Economics", 3, True),
        ("Non-Technical", "NTS3050", "Introduction to Logistics Management", 3, False),
        ("Non-Technical", "NTS4020", "Korean Technology Development Strategy", 3, False),
        ("Non-Technical", "NTS4050", "Understanding Intellectual Property Rights", 3, False),
        ("Non-Technical", "NTS3020", "Engineering Communications", 3, True),
        ("Non-Technical", "NTS4010", "Engineering Ethics", 2, True),
        ("Non-Technical", "NTS4060", "Distinguished Lecture in Social Science and Art", 2, False),
        (
            "Non-Technical",
            "NTS4070",
            "Distinguished Lecture in Natural Science and Technology",
            2,
            False,
        ),
        ("Non-Technical", "NTS4080", "Comtemporary Topics and Trends", 2, False),
        (
            "Non-Technical",
            "NTS3031",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-1",
            1,
            True,
        ),
        (
            "Non-Technical",
            "NTS3032",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-2",
            1,
            True,
        ),
        ("Technical Fundamental", "MSC1010", "Math Pre-calculus", 3, False),
        ("Technical Fundamental", "MSC1011", "Calculus 1", 3, True),
        ("Technical Fundamental", "MSC1012", "Calculus 2", 3, True),
        ("Technical Fundamental", "MSC2010", "Engineering Mathematics", 3, True),
        ("Technical Fundamental", "MSC2020", "Linear Algebra", 3, True),
        ("Technical Fundamental", "MSC2050", "Discrete Mathematics", 3, True),
        ("Technical Fundamental", "MSC3010", "Probability and Statistics", 3, True),
        ("Technical Fundamental", "MSC1020", "Science Pre-physics", 3, False),
        ("Technical Fundamental", "MSC1021", "Physics 1", 3, True),
        ("Technical Fundamental", "MSC1022", "Physics 2", 3, True),
        ("Technical Fundamental", "MSC1031", "Physics Experiment 1", 1, True),
        ("Technical Fundamental", "MSC1032", "Physics Experiment 2", 1, True),
        ("Technical Fundamental", "MSC1051", "Object-Oriented Programming 1", 3, True),
        ("Technical Fundamental", "MSC1052", "Object-Oriented Programming 2", 3, True),
        ("Technical Fundamental", "MSC2070", "Application Programming in Java", 3, True),
        ("Technical Core", "CSE1010", "Introduction to IT", 3, True),
        ("Technical Core", "CSE1020", "Creative Engineering Design", 3, True),
        ("Technical Core", "CSE2010", "Data Structure", 3, True),
        ("Technical Core", "SOC2020", "Digital Logic Circuit", 3, True),
        ("Technical Core", "SOC2040", "System Programming", 3, True),
        ("Technical Core", "SOC3030", "Computer Algorithm", 3, True),
        ("Technical Core", "SOC3010", "Operating System", 3, True),
        ("Technical Core", "SOC3020", "Database", 3, True),
        ("Technical Core", "SOC3040", "Computer Networks", 3, True),
        ("Technical Core", "CSE4020", "Capstone Design", 3, True),
        ("Technical Elective", "CSE2120", "Circuit and Lab", 3, False),
        ("Technical Elective", "SOC2110", "Internet Programming", 3, False),
        ("Technical Elective", "SOC2060", "Computer Architecture", 3, False),
        ("Technical Elective", "SOC3050", "Embedded Software & Design", 3, False),
        ("Technical Elective", "CSE2090", "Signals and Systems", 3, False),
        ("Technical Elective", "SOC3060", "Database Application & Design", 3, False),
        ("Technical Elective", "SOC3070", "System Analysis", 3, False),
        ("Technical Elective", "CSE3070", "Unix Programming", 3, False),
        ("Technical Elective", "SOC4010", "Computer Security", 3, False),
        ("Technical Elective", "SOC4020", "Multimedia Computing", 3, False),
        ("Technical Elective", "SOC4030", "Mobile Programming", 3, False),
        ("Technical Elective", "SOC4040", "Artificial Intelligence", 3, False),
        ("Technical Elective", "SOC4050", "Computer Graphics", 3, False),
        ("Technical Elective", "SOC4060", "Game Programming", 3, False),
        ("Technical Elective", "CSE4070", "Software Engineering", 3, False),
        ("Technical Elective", "SOC4080", "Multimedia Application", 3, False),
        ("Technical Elective", "SOC4090", "E-Commerce", 3, False),
        ("Technical Elective", "SOC4100", "Information Systems Security", 4, False),
        ("Technical Elective", "SOC4110", "Internet of Things", 3, False),
        ("Technical Elective", "SOC4120", "Mobile Communication", 3, False),
        ("Technical Elective", "SOC4130", "Data Communication", 3, False),
        ("Technical Elective", "SOC4140", "Theory of Programming language", 3, False),
        ("Technical Elective", "SOC4150", "Wireless Communications", 3, False),
        ("Technical Elective", "SOC4170", "Big Data Analytics", 3, False),
        ("Technical Elective", "SOC4180", "Deep Learning for Computer Vision", 3, False),
        ("Technical Elective", "CSE4110", "Compiler", 3, False),
        ("Technical Elective", "CSE4011", "Internship 1", 3, False),
        ("Technical Elective", "CSE4012", "Internship 2", 3, False),
    ],
    "BA": [
        ("General", "GEN1311", "Business English 1", 2, True),
        ("General", "GEN1312", "Business English 2", 2, True),
        ("General", "GEN2311", "Business English 3", 2, True),
        ("General", "GEN2312", "Business English 4", 2, True),
        ("General", "GEN3311", "Business English Readings & Writings 1", 2, True),
        ("General", "GEN3312", "Business English Readings & Writings 2", 2, True),
        ("General", "GEN2033", "Basic Korean 1", 2, False),
        ("General", "GEN2034", "Basic Korean 2", 2, False),
        ("Non-Technical", "NTS2010", "Distinguished Lecture Series", 2, False),
        (
            "Non-Technical",
            "NTS3031",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-1",
            1,
            True,
        ),
        (
            "Non-Technical",
            "NTS3032",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-2",
            1,
            True,
        ),
        ("Non-Technical", "NTS4050", "Understanding Intellectual Property Rights", 3, False),
        ("Non-Technical", "NTS4060", "International Commercial Law", 3, False),
        ("Non-Technical", "NTS3310", "Business Ethics", 2, True),
        ("Technical Fundamental", "TSF1311", "Statistics 1", 3, True),
        ("Technical Fundamental", "TSF1312", "Statistics 2", 3, True),
        ("Technical Fundamental", "TSF1320", "Business Mathematics", 3, True),
        ("Technical Fundamental", "TSF1330", "Computer Programming", 3, True),
        ("Technical Fundamental", "TSF1340", "Principle of Management", 3, True),
        ("Technical Fundamental", "TSF1350", "Introduction to Economics", 3, True),
        ("Technical Fundamental", "TSF1360", "Logistics Management", 3, True),
        ("Technical Fundamental", "TSF1370", "Introduction to Global Economy", 3, True),
        ("Technical Sequence", "TSM3350", "Product and Brand Management", 3, False),
        ("Technical Sequence", "TSL2310", "Supply Chain Management", 3, False),
        ("Technical Sequence", "TSM4320", "Consumer Behavior", 3, False),
        ("Technical Sequence", "TSM2340", "Human Resource Management", 3, False),
        ("Technical Sequence", "TSM2310", "Operations Research", 3, False),
        ("Technical Sequence", "TSM3310", "Financial Management", 3, False),
        ("Technical Sequence", "TSM2330", "Principles of Accounting", 3, False),
        ("Technical Sequence", "TSM3330", "Digital Marketing", 3, False),
        ("Technical Sequence", "TSM3340", "Operations Management", 3, False),
        ("Technical Sequence", "TSM2320", "Marketing Management", 3, False),
        ("Technical Sequence", "TSM3360", "Investments", 3, False),
        ("Technical Sequence", "TSL3360", "Trade Business", 3, False),
        ("Technical Sequence", "TSM3320", "Managerial Accounting", 3, False),
        ("Technical Sequence", "TSM4360", "Financial Institutions Management", 3, False),
        ("Technical Sequence", "TSL4330", "Manufacturing Logistics", 3, False),
        ("Technical Sequence", "TSL4340", "Logistics Network Analysis", 3, False),
        ("Technical Sequence", "TSL4350", "Logistics Information System", 3, False),
        ("Technical Sequence", "TSM4330", "Six Sigma Quality Management", 3, False),
        ("Technical Sequence", "TSM4340", "Channel Management", 3, False),
        ("Technical Sequence", "TSM4350", "Corporate Finance", 3, False),
        ("Technical Sequence", "TSL3330", "Logistics System Analysis", 3, False),
        ("Technical Sequence", "TSL4310", "Multimodal Transportation", 3, False),
        ("Technical Sequence", "TSL4320", "Logistics Demand Analysis", 3, False),
        ("Technical Sequence", "TSM4310", "Supply Chain Finance", 3, False),
        ("Technical Sequence", "TSE1310", "Organizational Behavior", 3, False),
        ("Technical Sequence", "TSE2310", "Business Strategy", 3, False),
        ("Technical Sequence", "TSE2320", "Entrepreneurship", 3, False),
        ("Technical Sequence", "TSE3310", "Project Management", 3, False),
        ("Technical Sequence", "TSN1310", "Management Information System", 3, False),
        ("Technical Sequence", "TSN2310", "Database Management", 3, False),
        ("Technical Sequence", "TSN3310", "BPR & ERP", 3, False),
        ("Technical Sequence", "TSN3330", "E-commerce", 3, False),
        ("Technical Sequence", "TSE4310", "Management of Venture Business", 3, False),
        ("Technical Sequence", "TSE4320", "Capstone Design for Business Modeling", 3, False),
        ("Technical Sequence", "TSN4310", "Corporate Bigdata Analysis", 3, False),
        ("Technical Sequence", "TSN4320", "System Analysis and Design", 3, False),
        ("Internship", "TSI4311", "Internship 1", 12, False),
        ("Internship", "TSI4312", "Internship 2", 12, False),
    ],
    "SBL": [
        ("General", "GEN1311", "Business English 1", 2, True),
        ("General", "GEN1312", "Business English 2", 2, True),
        ("General", "GEN2311", "Business English 3", 2, True),
        ("General", "GEN2312", "Business English 4", 2, True),
        ("General", "GEN3311", "Business English Readings & Writings 1", 2, True),
        ("General", "GEN3312", "Business English Readings & Writings 2", 2, True),
        ("General", "GEN2033", "Basic Korean 1", 2, False),
        ("General", "GEN2034", "Basic Korean 2", 2, False),
        ("Non-Technical", "NTS2010", "Distinguished Lecture Series", 2, False),
        (
            "Non-Technical",
            "NTS3031",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-1",
            1,
            True,
        ),
        (
            "Non-Technical",
            "NTS3032",
            "The New History of Uzbekistan, Philosophy, Basics of Spirituality and Jurisprudence-2",
            1,
            True,
        ),
        ("Non-Technical", "NTS4050", "Understanding Intellectual Property Rights", 3, False),
        ("Non-Technical", "NTS4060", "International Commercial Law", 3, False),
        ("Non-Technical", "NTS3310", "Business Ethics", 2, True),
        ("Technical Fundamental", "TSF1311", "Statistics 1", 3, True),
        ("Technical Fundamental", "TSF1312", "Statistics 2", 3, True),
        ("Technical Fundamental", "TSF1320", "Business Mathematics", 3, True),
        ("Technical Fundamental", "TSF1330", "Computer Programming", 3, True),
        ("Technical Fundamental", "TSF1340", "Principle of Management", 3, True),
        ("Technical Fundamental", "TSF1350", "Introduction to Economics", 3, True),
        ("Technical Fundamental", "TSF1360", "Logistics Management", 3, True),
        ("Technical Fundamental", "TSF1370", "Introduction to Global Economy", 3, True),
        ("Technical Sequence", "TSL1310", "Transportation Economics", 3, False),
        ("Technical Sequence", "TSL2310", "Supply Chain Management", 3, False),
        ("Technical Sequence", "TSL2320", "International Logistics", 3, False),
        ("Technical Sequence", "TSL2330", "Freight Transportation", 3, False),
        ("Technical Sequence", "TSM2310", "Operations Research", 3, False),
        ("Technical Sequence", "TSM3310", "Financial Management", 3, False),
        ("Technical Sequence", "TSM2330", "Principles of Accounting", 3, False),
        ("Technical Sequence", "TSL3310", "Railway Transportation", 3, False),
        ("Technical Sequence", "TSL3320", "Air Transportation", 3, False),
        ("Technical Sequence", "TSM2320", "Marketing Management", 3, False),
        ("Technical Sequence", "TSL3340", "Warehousing and Material Handling", 3, False),
        ("Technical Sequence", "TSL3360", "Trade Business", 3, False),
        ("Technical Sequence", "TSM3320", "Managerial Accounting", 3, False),
        ("Technical Sequence", "TSM4360", "Financial Institutions Management", 3, False),
        ("Technical Sequence", "TSL4330", "Manufacturing Logistics", 3, False),
        ("Technical Sequence", "TSL4340", "Logistics Network Analysis", 3, False),
        ("Technical Sequence", "TSL4350", "Logistics Information System", 3, False),
        ("Technical Sequence", "TSM4330", "Six Sigma Quality Management", 3, False),
        ("Technical Sequence", "TSM4340", "Channel Management", 3, False),
        ("Technical Sequence", "TSM4350", "Corporate Finance", 3, False),
        ("Technical Sequence", "TSL3330", "Logistics System Analysis", 3, False),
        ("Technical Sequence", "TSL4310", "Multimodal Transportation", 3, False),
        ("Technical Sequence", "TSL4320", "Logistics Demand Analysis", 3, False),
        ("Technical Sequence", "TSM4320", "Consumer Behavior", 3, False),
        ("Technical Sequence", "TSM4310", "Supply Chain Finance", 3, False),
        ("Technical Sequence", "TSE1310", "Organizational Behavior", 3, False),
        ("Technical Sequence", "TSE2310", "Business Strategy", 3, False),
        ("Technical Sequence", "TSE2320", "Entrepreneurship", 3, False),
        ("Technical Sequence", "TSE3310", "Project Management", 3, False),
        ("Technical Sequence", "TSN1310", "Management Information System", 3, False),
        ("Technical Sequence", "TSN2310", "Database Management", 3, False),
        ("Technical Sequence", "TSN3310", "BPR & ERP", 3, False),
        ("Technical Sequence", "TSN3330", "E-commerce", 3, False),
        ("Technical Sequence", "TSE4310", "Management of Venture Business", 3, False),
        ("Technical Sequence", "TSE4320", "Capstone Design for Business Modeling", 3, False),
        ("Technical Sequence", "TSN4310", "Corporate Bigdata Analysis", 3, False),
        ("Technical Sequence", "TSN4320", "System Analysis and Design", 3, False),
        ("Internship", "TSI4311", "Internship 1", 12, False),
        ("Internship", "TSI4312", "Internship 2", 12, False),
    ],
}
